# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description_text',
            field=models.TextField(default='Put description here', max_length=400),
        ),
    ]
