# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 20:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0002_topic_description_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='replies',
            new_name='number_of_replies',
        ),
    ]
