# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 19:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topics', '0003_auto_20160729_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replies_to_this', models.ManyToManyField(related_name='_reply_replies_to_this_+', to='topics.Reply')),
                ('reply_in_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Reply')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replies_posted', models.ManyToManyField(to='topics.Reply')),
            ],
        ),
        migrations.AlterField(
            model_name='topic',
            name='description_text',
            field=models.TextField(default='Put description here', max_length=2000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='topics_posted',
            field=models.ManyToManyField(to='topics.Topic'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reply',
            name='topic_in_reply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Topic'),
        ),
        migrations.AddField(
            model_name='reply',
            name='user_who_posted',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
